apps/crud_users_web/lib/crud_users_web/router.ex
defmodule CrudUsersWeb.Router do
  use CrudUsersWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CrudUsersWeb do
    pipe_through :browser
    get "/", PageController, :index
    post "/create_form", UserController, :create_form
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", CrudUsersWeb do
    pipe_through :api
    #Forma 2 de declarar rutas
    resources "/users", UserController, only: [:index, :show, :create]
    #Forma 1 de declarar rutas
    #post "/users", UserController, :create
    #get "/users", UserController, :index
    #get "/users/:id", UserController, :show
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: CrudUsersWeb.Telemetry
    end
  end
end

apps/crud_users_web/lib/crud_users_web/controllers/page_controller.ex
defmodule CrudUsersWeb.PageController do
  use CrudUsersWeb, :controller

  def index(conn, _params) do
    changeset = CrudUsers.User.signup_changeset(%CrudUsers.User{})
    render(conn, "crud.html", changeset: changeset)
  end
end

apps/crud_users_web/lib/crud_users_web/controllers/user_controller.ex
defmodule CrudUsersWeb.UserController do
  use CrudUsersWeb, :controller
  alias CrudUsers.User
  #Controlador que atrapa o maneja errores
  action_fallback CrudUsersWeb.UserFallBackController
  def create(conn, %{"user" => user_params}) do
    chg = User.signup_changeset(%User{}, user_params)
    case chg.valid? do
      true ->
        {:ok, user} = User.save(chg)
        conn
          |> put_status(201)
          #Forma 2 con uso de vistas (view)
          |> render("single_user.json", %{user: user})
          #Forma 1 con json
          #|> json(%{user: %{name: user.name, age: user.age, email: user.email}})
      false ->
        conn
          |> put_status(400)
          |> render("error.json", changeset: chg)
          #|> json(%{error: "Error al crear el usuario"})
    end
  end
  #funcion que usamos para guardar los datos del formulario en la bd
  def create_form(conn, %{"user" => user} = params) do
    IO.inspect params
    User.signup_changeset(%User{}, user)
    |> User.save()
    redirect(conn, to: Routes.page_path(conn, :index))
    #[[:to,]]
    #render(conn, :index)
  end
  def index(conn, _params) do
    users = User.search_all
    IO.inspect users
    if users do
      conn
        |> put_status(200)
        |> render("users.json", %{users: users})
        #|> json(%{users_active: [users]})
    else
      conn
        |> put_status(400)
        |> json(%{ok: false, msg: "Error en la peticion"})
    end
  end
  def show(conn, %{"id" => id}) do
    user = User.search(id)
    IO.inspect user
    if user do
      conn
        |> put_status(200)
        |> json(%{user: %{name: user.name, age: user.age, email: user.email}})
    else
      conn
        |> put_status(404)
        |> json(%{ok: false, msg: "Usuario no encontrado"})
    end
  end
end

apps/crud_users_web/lib/crud_users_web/error_controllers/user_error_controller.ex
defmodule CrudUsersWeb.UserFallBackController do
  #modulo creado para cachar los errores
  use CrudUsersWeb, :controller
  def call(conn, {:error, changeset = %Ecto.Changeset{}}) do
    IO.inspect changeset
      conn
        |> put_status(400)
        |> json(%{errors: "Change Set Errors"})
  end
  def call(conn, {:error, error}) do
    conn
      |> put_status(404)
      |> json(%{error: error})
  end
  def call(conn, _) do
    conn
      |> put_status(500)
      |> json(%{error: "Unhaundled error: please call administrator"})
  end
end

apps/crud_users_web/lib/crud_users_web/views/error_view.ex
defmodule CrudUsersWeb.ErrorView do
  use CrudUsersWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/crud_users_web/lib/crud_users_web/views/layout_view.ex
defmodule CrudUsersWeb.LayoutView do
  use CrudUsersWeb, :view
end

apps/crud_users_web/lib/crud_users_web/views/page_view.ex
defmodule CrudUsersWeb.PageView do
  use CrudUsersWeb, :view
end

apps/crud_users_web/lib/crud_users_web/views/user_view.ex
defmodule CrudUsersWeb.UserView do
  #vista creada para el manejon de erroes en el archivo  user_controller en la linea 15
  use CrudUsersWeb, :view
  alias CrudUsersWeb.UserView

  def transalate_errors(changeset) do
    Ecto.Changeset.traverse_errors(changeset, &translate_error/1)
  end
  def render("error.json", %{changeset: changeset}) do
    %{errors: transalate_errors(changeset)}
  end
  #vista creada para visualizar los json
  def render("single_user.json", %{user: user}) do
    %{
      name: user.name,
      age: user.age,
      email: user.email,
      id: user.id
    }
  end
  #vista creada para visualizar a todos los usuarios de la bd
  def render("users.json", %{users: users}) do
    %{users: render_many(users, UserView, "single_user.json")}
  end
end

apps/crud_users_web/lib/crud_users_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>CrudUsers · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul style="font-size: 13pt">
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <%= @inner_content %>
    </main>
  </body>
</html>

apps/crud_users_web/lib/crud_users_web/templates/page/crud.html.eex
<h3 class="text-info">CRUD WITH PHOENIX</h3>
<%= form_for @changeset, Routes.user_path(@conn, :create_form), fn f -> %>
    <div class="row">
        <div class="input-group input-group-sm mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Nombre:</span>
            </div>
            <%= text_input f, :name, class: "form-control" %>
        </div>
        <div class="input-group input-group-sm mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Email:</span>
            </div>
            <%= text_input f, :email, class: "form-control" %>
        </div>
        <div class="input-group input-group-sm mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Edad:</span>
            </div>
            <%= text_input f, :age, class: "form-control" %>
        </div>
    </div>
    <div class="row justify-content-center">
        <%= submit "Guardar usuario", class: "btn btn-outline-success btn-sm" %>
    </div>
<% end %>

apps/crud_users_web/lib/crud_users_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>Peace of mind from prototype to production</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.5/CHANGELOG.md">v1.5 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
      <li>
        <a href="https://elixir-slackin.herokuapp.com/">Elixir on Slack</a>
      </li>
    </ul>
  </article>
</section>